sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
 - docker pull apiman/on-wildfly10:latest
script:
 - docker run -d -p 8080:8080 apiman/on-wildfly10:latest
 - ./gradlew test -PintegrationTest --info
